### ISSUE TITLE
Style Home Page

### ISSUE THREAD

**Issue by osondoar** [rubyforgood/justice#1]
## Overview
This is the page all users will use as their home page. This is also where the logo and home menu item will link to.

## Hero Section
This above the fold section will have 3 blocks that can be configured by Site Admins. One large block (640px x 488px) to the left of two blocks half the height of the larger one (320x244). Elements for each of the blocks are the same:
* Image (cropped on render to correct dimensions to fill 100% of the block as a background)
* Text
* URL for text to link to

## Content Section
This is a WYSIWYG that allows Site Admins to have control over this area.

## Right Sidebar Section
If blocks are placed in this section they will show up. It should be 300px in width and if not present will not be rendered allowing the content section to span 100% of the width.

## Permissions
Permissions|Authentication Details
---|---
Public | This is a publicly-viewable page, so it will be able to be accessed by anyone without logging in.
Private | Editing of this page is private (by site admins).

## Mockups
https://wireframe.cc/pro/pp/973dd11fc84472

**Comment by jmkoni** [comment]
Completed with:
https://github.com/rubyforgood/justice/pull/19
https://github.com/rubyforgood/justice/pull/21

**Comment by osondoar** [comment]
#79 completes this.
