### ISSUE TITLE
Basic Page

### ISSUE THREAD

**Issue by osondoar** [rubyforgood/justice#2]
## Overview
This is a content type that can be used to add internal pages for various uses.

## Hero Section

This above the fold section will have a single image that spans full width that can be configured by Site Admins.

## Content Section
This is a WYSIWYG that allows Site Admins to have control over this area.

## Right Sidebar Section
If blocks are placed in this section they will show up. It should be 300px in width and if not present will not be rendered allowing the content section to span 100% of the width.

## Permissions
Permissions|Authentication Details
---|---
Public | This is a publicly-viewable page, so it will be able to be accessed by anyone without logging in.
Private | Editing of this page is private (by site admins).

## Mockups
https://wireframe.cc/pro/pp/24455d09c84483

**Comment by jmkoni** [comment]
Completed with https://github.com/rubyforgood/justice/pull/21
