### ISSUE TITLE
Lesson Listing Page

### ISSUE THREAD

**Issue by osondoar** [rubyforgood/justice#4]
## Overview
This pages shows all of the lessons on the site. This is where volunteers can easily locate lessons for use during sessions.

## Create New Button
Allows the user to create a new lesson.
## Filters Section
Helps volunteers more easily locate specific lessons.
* Title – searches for titles that contain the search text
* Type (single-select) – filters on the lesson “type” field
* Term (multi-select) – filters on the lesson “terms” field

## Lesson List Section
Displays all of the lessons or just those that match the filters. This section is paginated showing 50 lessons per page.
Columns:
* Title
* Type
* Terms – comma-separated list of terms associated with the lesson. Each will link to a filtered lesson listing page that is filtered on the term selected
* Created – creation date of the lesson

## Permissions
Permissions|Authentication Details
---|---
Private | This is a privately-viewable page, so it will be able to be accessed by only those with appropriate permissions: Volunteers and Site Admins

## Mockups
https://wireframe.cc/pro/pp/0e83656a984547

**Comment by jmkoni** [comment]
https://github.com/rubyforgood/justice/pull/27
